apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: messaging-app
data:
  init.sql: |
    -- MySQL initialization script
    -- This script runs when the MySQL container starts for the first time

    -- Set character set and collation
    SET NAMES utf8mb4;
    SET CHARACTER SET utf8mb4;
    SET collation_connection = 'utf8mb4_unicode_ci';

    -- Create database if it doesn't exist
    CREATE DATABASE IF NOT EXISTS `messaging_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- Grant privileges to the user
    GRANT ALL PRIVILEGES ON `messaging_db`.* TO 'messaging_user'@'%';
    FLUSH PRIVILEGES;

    -- Show databases
    SHOW DATABASES;
