pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }

    environment {
        VENV_DIR = '.venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/reuben-idan/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python -m venv $VENV_DIR'
                sh '. $VENV_DIR/bin/activate && pip install --upgrade pip pytest'
                sh '. $VENV_DIR/bin/activate && pip install -r messaging_app/requirements.txt || pip install -r messaging_app/requirement.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. $VENV_DIR/bin/activate && pytest messaging_app --junitxml=report.xml'
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    options {
        disableConcurrentBuilds()
    }

    triggers {
        // manual trigger only
    }
} 