#!/bin/bash

# Apply both deployments
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

# Check logs for green
echo "Checking logs for green deployment..."
kubectl logs -l app=django,version=green

# Apply service (starts with blue, change to green manually or via script later)
kubectl apply -f kubeservice.yaml
